" alpizape's vimrc file

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

set ch=2		" set command line to 2 lines high
set sw=2		" used for cindent, smartindent and autoindent for the number
			"   of columns to indent
set sts=2		" used to make the <Tab> key look like tabs are 'sw' spaces long
			"  but actually inserts spaces and tabs, preserving the default 'ts'
set expandtab           " Used to insert spaces when you press tab
set tabstop=2           " Set the spaces to 2
set shiftwidth=2        " Set to 2
set bs=indent,eol,start	" allow backspacing over everything in insert mode
set ai			" always set autoindenting on
"set backup		" keep a backup file
set viminfo='100,\"500,:20
			" read/write a .viminfo file, don't keep marks for more
			" than 100 files, don't keep more
			" than 500 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set magic
set noeb		" no errorbells
set vb t_vb=""		" for all other bells set visual bell and make the 
			"	character written to the screen the empty
			"	string so the screen will not flash
set incsearch		" set incremental search: moves through the file as the
			"   pattern changes
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
" set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching


" Don't use Ex mode, use Q for formatting
"map Q gq

" Make p in Visual mode replace the selected text with the "" register
vnoremap p <Esc>:let current_reg = @"<CR>gvdi<C-R>=current_reg<CR><Esc>

syntax on
" highlight the matches in a search
set hlsearch
"set mouse=a

if $DVORAK
    noremap h j
    noremap d h
    noremap t k
    noremap n l
endif

map ;; :%s:::g<Left><Left><Left>
"map ;' :%s:::cg<Left><Left><Left>
map tp :tabprevious
map tf :tabnext
map tl :TlistOpen
map tn :tabnew

"colorscheme slate
set number


